package mikey.me.antiBase;

import org.bukkit.Material;
import org.bukkit.block.BlockFace;
import org.bukkit.block.BlockSupport;
import org.bukkit.block.data.BlockData;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ChestVisibilityTest {
    // measured on a real paper runtime, regenerated by PaperChestVerification.
    // replayed here so normal unit tests dont need to boot minecraft
    record Profile(String state, boolean canOcclude, Set<BlockFace> fullFaces, int expected) {
        @Override public String toString() { return state; }
        BlockData data() {
            BlockData data = mock(BlockData.class);
            when(data.isOccluding()).thenReturn(canOcclude);
            when(data.getMaterial()).thenReturn(Material.valueOf(state.substring(10, state.indexOf('[')).toUpperCase(java.util.Locale.ROOT)));
            when(data.isFaceSturdy(any(BlockFace.class), eq(BlockSupport.FULL)))
                    .thenAnswer(call -> fullFaces.contains(call.getArgument(0)));
            return data;
        }
    }

    static List<Profile> profiles() throws Exception {
        var resource = ChestVisibilityTest.class.getResourceAsStream("/paper-1.21.11-chest-shapes.tsv");
        if (resource == null) throw new IllegalStateException("Missing captured Paper chest shapes");
        try (var reader = new BufferedReader(new InputStreamReader(resource, StandardCharsets.UTF_8))) {
            return reader.lines().filter(line -> !line.startsWith("#") && !line.isBlank()).map(line -> {
                String[] fields = line.split("\t", -1);
                Set<BlockFace> faces = fields[2].isEmpty() ? Set.of()
                        : Arrays.stream(fields[2].split(",")).map(BlockFace::valueOf).collect(Collectors.toSet());
                return new Profile(fields[0], Boolean.parseBoolean(fields[1]), faces, Integer.parseInt(fields[3]));
            }).toList();
        }
    }

    @Test void profilesCoverEveryChestVariant() throws Exception {
        Map<String, Long> counts = profiles().stream().collect(Collectors.groupingBy(
                profile -> profile.state.substring(10, profile.state.indexOf('[')), Collectors.counting()));
        assertEquals(12, counts.size()); // 11 chest materials + barrel
        assertEquals(8L, counts.get("ender_chest"));
        assertEquals(12L, counts.get("barrel"));
        counts.forEach((material, count) -> {
            if (!material.equals("ender_chest") && !material.equals("barrel")) assertEquals(24L, count, material);
        });
    }

    @ParameterizedTest(name="{0}") @MethodSource("profiles")
    void realChestProfilesKeepGapsOpen(Profile profile) {
        BlockData opening = profile.data();
        assertEquals(profile.expected, BlockOcclusion.classify(opening));
        PaperChestVerification.checkRoom(profile.state, opening, air(), stone(), profile.expected == 2);
    }

    static Stream<Profile> doubleChests() throws Exception {
        return profiles().stream().filter(profile -> profile.state.contains("type=left"));
    }

    @ParameterizedTest(name="paired across chunk boundary: {0}") @MethodSource("doubleChests")
    void doubleChestHalvesRevealRoomAcrossChunks(Profile left) throws Exception {
        String rightState = left.state.replace("type=left", "type=right");
        Profile right = profiles().stream().filter(profile -> profile.state.equals(rightState)).findFirst().orElseThrow();
        BlockData leftData = left.data(), rightData = right.data(), air = air(), stone = stone();
        String facing = left.state.split("facing=")[1].split(",")[0];
        int frontX = facing.equals("east") ? 1 : facing.equals("west") ? -1 : 0;
        int frontZ = facing.equals("south") ? 1 : facing.equals("north") ? -1 : 0;
        int acrossX = -frontZ, acrossZ = frontX;
        int originX = acrossX < 0 ? 16 : 15, originZ = acrossZ < 0 ? 16 : 15;
        int rightX = originX + acrossX, rightZ = originZ + acrossZ;
        assertTrue((originX >> 4) != (rightX >> 4) || (originZ >> 4) != (rightZ >> 4));
        VisibilityScanner.BlockAccess map = (x, y, z) -> {
            int u = (x - originX) * acrossX + (z - originZ) * acrossZ;
            int depth = -(x - originX) * frontX - (z - originZ) * frontZ;
            BlockData data = stone;
            if (y == -10 && u >= 0 && u <= 1 && depth >= -1 && depth <= 5) {
                data = depth == 0 ? (u == 0 ? leftData : rightData) : air;
            }
            return BlockOcclusion.classify(data);
        };
        VisibilitySnapshot visible = ConnectedVisibilityScanner.scan(map,
                originX + frontX + .5, -9.5, originZ + frontZ + .5, -32, 0, 0, 16);
        assertTrue(visible.isTerrainVisible(originX, -10, originZ));
        assertTrue(visible.isTerrainVisible(rightX, -10, rightZ));
        for (int u = 0; u <= 1; u++) {
            int x = originX + u * acrossX, z = originZ + u * acrossZ;
            assertTrue(visible.isConnected(x - frontX * 5, -10, z - frontZ * 5));
            assertTrue(visible.isTerrainVisible(x - frontX * 6, -10, z - frontZ * 6));
            assertFalse(visible.isBlockVisible(x - frontX * 7, -10, z - frontZ * 7));
        }
    }

    private static BlockData air() {
        BlockData data = mock(BlockData.class);
        when(data.getMaterial()).thenReturn(Material.AIR);
        return data;
    }

    private static BlockData stone() {
        BlockData data = mock(BlockData.class);
        when(data.isOccluding()).thenReturn(true);
        when(data.isFaceSturdy(any(BlockFace.class), eq(BlockSupport.FULL))).thenReturn(true);
        return data;
    }
}
